MAPA = [
    # ['Cidade'       , 'Estado'              , 'Sigla' , 'Região'       ] ,
    ['Rio Branco'     , 'Acre'                , 'AC' , 'Norte'        ] ,
    ['Maceió'         , 'Alagoas'             , 'AL' , 'Nordeste'     ] ,
    ['Macapá'         , 'Amapá'               , 'AP' , 'Norte'        ] ,
    ['Manaus'         , 'Amazonas'            , 'AM' , 'Norte'        ] ,
    ['Salvador'       , 'Bahia'               , 'BA' , 'Nordeste'     ] ,
    ['Fortaleza'      , 'Ceará'               , 'CE' , 'Nordeste'     ] ,
    ['Brasília*'      , 'Distrito Federal'    , 'DF' , 'Centro-Oeste' ] ,
    ['Vitória'        , 'Espírito Santo'      , 'ES' , 'Sudeste'      ] ,
    ['Goiânia'        , 'Goiás'               , 'GO' , 'Centro-Oeste' ] ,
    ['São Luís'       , 'Maranhão'            , 'MA' , 'Nordeste'     ] ,
    ['Cuiabá'         , 'Mato Grosso'         , 'MT' , 'Centro-Oeste' ] ,
    ['Campo Grande'   , 'Mato Grosso do Sul'  , 'MS' , 'Centro-Oeste' ] ,
    ['Belo Horizonte' , 'Minas Gerais'        , 'MG' , 'Sudeste'      ] ,
    ['Belém'          , 'Pará'                , 'PA' , 'Norte'        ] ,
    ['João Pessoa'    , 'Paraíba'             , 'PB' , 'Nordeste'     ] ,
    ['Curitiba'       , 'Paraná'              , 'PR' , 'Sul'          ] ,
    ['Recife'         , 'Pernambuco'          , 'PE' , 'Nordeste'     ] ,
    ['Teresina'       , 'Piauí'               , 'PI' , 'Nordeste'     ] ,
    ['Rio de Janeiro' , 'Rio de Janeiro'      , 'RJ' , 'Sudeste'      ] ,
    ['Natal'          , 'Rio Grande do Norte' , 'RN' , 'Nordeste'     ] ,
    ['Porto Alegre'   , 'Rio Grande do Sul'   , 'RS' , 'Sul'          ] ,
    ['Porto Velho'    , 'Rondônia'            , 'RO' , 'Norte'        ] ,
    ['Boa Vista'      , 'Roraima'             , 'RR' , 'Norte'        ] ,
    ['Florianópolis'  , 'Santa Catarina'      , 'SC' , 'Sul'          ] ,
    ['São Paulo'      , 'São Paulo'           , 'SP' , 'Sudeste'      ] ,
    ['Aracaju'        , 'Sergipe'             , 'SE' , 'Nordeste'     ] ,
    ['Palmas'         , 'Tocantins'           , 'TO' , 'Norte'        ] ,
]

FRONTEIRAS = {
    'AC': ['AM', 'RO'],
    'AL': ['BA', 'PE', 'SE'],
    'AM': ['AC', 'PA', 'RO', 'RR', 'MT'],
    'AP': ['PA'],
    'BA': ['AL', 'GO', 'MG', 'ES', 'PE', 'PI', 'TO', 'SE'],
    'CE': ['RN', 'PI', 'PB', 'PE'],
    'DF': ['GO', 'MG'],
    'ES': ['BA', 'MG', 'RJ'],
    'GO': ['BA', 'DF', 'MG', 'MS', 'MT', 'TO'],
    'MA': ['PI', 'PA', 'TO'],
    'MG': ['DF', 'BA', 'GO', 'ES', 'RJ', 'SP', 'MS'],
    'MS': ['GO', 'MT', 'PR', 'SP', 'MG'],
    'MT': ['AM', 'PA', 'TO', 'GO', 'MS', 'RO'],
    'PA': ['AP', 'MA', 'TO', 'AM', 'RO', 'MT'],
    'PB': ['PE', 'RN', 'CE'],
    'PE': ['PB', 'CE', 'AL', 'BA', 'PI'],
    'PI': ['MA', 'CE', 'PE', 'BA', 'TO'],
    'PR': ['SC', 'SP', 'MS'],
    'RJ': ['ES', 'MG', 'SP'],
    'RN': ['PB', 'CE'],
    'RO': ['AM', 'AC', 'MT', 'PA'],
    'RR': ['AM'],
    'RS': ['SC'],
    'SC': ['PR', 'RS'],
    'SE': ['AL', 'BA'],
    'SP': ['MG', 'RJ', 'PR', 'MS'],
    'TO': ['MA', 'PI', 'BA', 'GO', 'MT', 'PA']
}

CUSTOS = { # TODO: Adicionar custos
    'AC': [''],                     
    'AL': ['', '', ''],
    'AM': ['', '', '', ''],
    'AP': [''],
    'BA': ['', '', '', '', '', '', '', ''],
    'CE': ['', '', '', ''],
    'DF': ['', ''],
    'ES': ['', '', ''],
    'GO': ['', '', '', '', '', ''],
    'MA': ['', '', ''],
    'MG': ['', '', '', '', '', '', ''],
    'MS': ['', '', '', '', ''],
    'MT': ['', '', '', '', '', ''],
    'PA': ['', '', '', '', '', ''],
    'PB': ['', '', ''],
    'PE': ['', '', '', '', ''],
    'PI': ['', '', '', '', ''],
    'PR': ['', '', ''],
    'RJ': ['', '', ''],
    'RN': ['', ''],
    'RO': ['', '', ''],
    'RR': [''],
    'RS': [''],
    'SC': ['', ''],
    'SE': ['', ''],
    'SP': ['', '', '', ''],
    'TO': ['', '', '', '', '', ''],
}
