MAPA = [
    # ['Cidade'       , 'Estado'              , 'Sigla' , 'Região'       ] ,
    ['Rio Branco'     , 'Acre'                , 'AC' , 'Norte'        ] ,
    ['Maceió'         , 'Alagoas'             , 'AL' , 'Nordeste'     ] ,
    ['Macapá'         , 'Amapá'               , 'AP' , 'Norte'        ] ,
    ['Manaus'         , 'Amazonas'            , 'AM' , 'Norte'        ] ,
    ['Salvador'       , 'Bahia'               , 'BA' , 'Nordeste'     ] ,
    ['Fortaleza'      , 'Ceará'               , 'CE' , 'Nordeste'     ] ,
    ['Brasília*'      , 'Distrito Federal'    , 'DF' , 'Centro-Oeste' ] ,
    ['Vitória'        , 'Espírito Santo'      , 'ES' , 'Sudeste'      ] ,
    ['Goiânia'        , 'Goiás'               , 'GO' , 'Centro-Oeste' ] ,
    ['São Luís'       , 'Maranhão'            , 'MA' , 'Nordeste'     ] ,
    ['Cuiabá'         , 'Mato Grosso'         , 'MT' , 'Centro-Oeste' ] ,
    ['Campo Grande'   , 'Mato Grosso do Sul'  , 'MS' , 'Centro-Oeste' ] ,
    ['Belo Horizonte' , 'Minas Gerais'        , 'MG' , 'Sudeste'      ] ,
    ['Belém'          , 'Pará'                , 'PA' , 'Norte'        ] ,
    ['João Pessoa'    , 'Paraíba'             , 'PB' , 'Nordeste'     ] ,
    ['Curitiba'       , 'Paraná'              , 'PR' , 'Sul'          ] ,
    ['Recife'         , 'Pernambuco'          , 'PE' , 'Nordeste'     ] ,
    ['Teresina'       , 'Piauí'               , 'PI' , 'Nordeste'     ] ,
    ['Rio de Janeiro' , 'Rio de Janeiro'      , 'RJ' , 'Sudeste'      ] ,
    ['Natal'          , 'Rio Grande do Norte' , 'RN' , 'Nordeste'     ] ,
    ['Porto Alegre'   , 'Rio Grande do Sul'   , 'RS' , 'Sul'          ] ,
    ['Porto Velho'    , 'Rondônia'            , 'RO' , 'Norte'        ] ,
    ['Boa Vista'      , 'Roraima'             , 'RR' , 'Norte'        ] ,
    ['Florianópolis'  , 'Santa Catarina'      , 'SC' , 'Sul'          ] ,
    ['São Paulo'      , 'São Paulo'           , 'SP' , 'Sudeste'      ] ,
    ['Aracaju'        , 'Sergipe'             , 'SE' , 'Nordeste'     ] ,
    ['Palmas'         , 'Tocantins'           , 'TO' , 'Norte'        ] ,
]

FRONTEIRAS = {
    'AC': ['AM', 'RO'],
    'AL': ['BA', 'PE', 'SE'],
    'AM': ['AC', 'PA', 'RO', 'RR', 'MT'],
    'AP': ['PA'],
    'BA': ['AL', 'GO', 'MG', 'ES', 'PE', 'PI', 'TO', 'SE'],
    'CE': ['RN', 'PI', 'PB', 'PE'],
    'DF': ['GO', 'MG'],
    'ES': ['BA', 'MG', 'RJ'],
    'GO': ['BA', 'DF', 'MG', 'MS', 'MT', 'TO'],
    'MA': ['PI', 'PA', 'TO'],
    'MG': ['DF', 'BA', 'GO', 'ES', 'RJ', 'SP', 'MS'],
    'MS': ['GO', 'MT', 'PR', 'SP', 'MG'],
    'MT': ['AM', 'PA', 'TO', 'GO', 'MS', 'RO'],
    'PA': ['AP', 'MA', 'TO', 'AM', 'RO', 'MT'],
    'PB': ['PE', 'RN', 'CE'],
    'PE': ['PB', 'CE', 'AL', 'BA', 'PI'],
    'PI': ['MA', 'CE', 'PE', 'BA', 'TO'],
    'PR': ['SC', 'SP', 'MS'],
    'RJ': ['ES', 'MG', 'SP'],
    'RN': ['PB', 'CE'],
    'RO': ['AM', 'AC', 'MT', 'PA'],
    'RR': ['AM'],
    'RS': ['SC'],
    'SC': ['PR', 'RS'],
    'SE': ['AL', 'BA'],
    'SP': ['MG', 'RJ', 'PR', 'MS'],
    'TO': ['MA', 'PI', 'BA', 'GO', 'MT', 'PA']
}

BELEZAS = {
    'AC': 3,  
    'AL': 6,  
    'AM': 6,  
    'AP': 3,  
    'BA': 8,  
    'CE': 7,  
    'DF': 8,  
    'ES': 7,  
    'GO': 5,  
    'MA': 5,  
    'MG': 7,  
    'MS': 4,  
    'MT': 4,  
    'PA': 5,  
    'PB': 6,  
    'PE': 8,  
    'PI': 4,  
    'PR': 9,  
    'RJ': 10, 
    'RN': 6,  
    'RO': 3,  
    'RR': 3,  
    'RS': 8,  
    'SC': 9,  
    'SE': 5,  
    'SP': 8,  
    'TO': 4,  
}

CUSTOS = { # TODO: Adicionar custos
    'AC': [1445, 544],                     
    'AL': [632, 285, 294],
    'AM': [1445, 5298, 901, 785, 2357],
    'AP': [528],
    'BA': [632, 1643, 1372, 1202, 839, 1163, 1454, 356],
    'CE': [537, 634, 688, 800],
    'DF': [209, 716],
    'ES': [1202, 524, 528],
    'GO': [1643, 209, 906, 935, 934, 874],
    'MA': [446, 806, 1386],
    'MG': [716, 1372, 906, 524, 434, 586, 528],
    'MS': [935, 694, 991, 1014, 528],
    'MT': [2357, 2941, 1784, 934, 694, 1456],
    'PA': [528, 806, 1283, 5298, 4397, 2941],
    'PB': [120, 185, 688],
    'PE': [120, 800, 285, 839, 1137],
    'PI': [446, 634, 1137, 1163, 1401],
    'PR': [300, 408, 991],
    'RJ': [528, 434, 429],
    'RN': [185, 537],
    'RO': [901, 544, 1456, 4397],
    'RR': [785],
    'RS': [476],
    'SC': [300, 476],
    'SE': [294, 356],
    'SP': [586, 521, 408, 1014],
    'TO': [1386, 1401, 1454, 874, 1784, 1283],
}
